Vagrant.configure(2) do |config|

   config.vm.box = "nritholtz/ubuntu-14.04.1"
  
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.name = "Perquimans-vaettap-xMapper"
     vb.memory = "2098"
     # Disable USB
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
   end

   config.vm.provision "shell", inline: <<-SHELL
    # Install Oracle Java 6
    sudo add-apt-repository -y ppa:webupd8team/java
    sudo apt-get update
    echo "oracle-java6-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
    sudo apt-get install -y oracle-java6-set-default
    
    # Install Adobe Flash Player plugin to view youtube videos
    sudo apt-get install -y flashplugin-installer 
    
    # Copy Eclipse and create shortcut
    cp /vagrant/eclipse.tar.gz /home/vagrant/Desktop/eclipse.tar.gz
    cd /home/vagrant/Desktop
    sudo tar -zxvf eclipse.tar.gz
    sudo chown -R vagrant /home/vagrant/Desktop/eclipse
    ln -s /home/vagrant/Desktop/eclipse/eclipse "/home/vagrant/Desktop/Eclipse"
    
    #Copy workspace
    sudo mkdir /home/vagrant/workspace
    cd /home/vagrant/workspace
    wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=0B5CDoggIha9BX2ltTUJqdkhMeDA' -O workspace.tar.gz
    sudo tar -zxvf workspace.tar.gz
    sudo chown -R vagrant /home/vagrant/workspace/
    
    # Add Eclipse as startup application
    sudo mkdir "/home/vagrant/.config/autostart"
    sudo chown -R vagrant "/home/vagrant/.config/autostart/"
    wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-xMapper/raw/master/build-vm/vm-contents/eclipse.desktop -O "/home/vagrant/.config/autostart/eclipse.desktop"
    sudo chown -R vagrant "/home/vagrant/.config/autostart/eclipse.desktop"
    
    # Copy readme, installation, licenses, how-to video links to vm desktop
    cd /home/vagrant/Desktop
    wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-xMapper/raw/master/build-vm/vm-contents/Installation.txt -O Installation.txt
    wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-xMapper/raw/master/build-vm/vm-contents/License.txt -O License.txt
    wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-xMapper/raw/master/build-vm/vm-contents/Readme.txt -O Readme.txt
    wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-xMapper/raw/master/build-vm/vm-contents/VM%20xMapper%20An%20Architecture-Implementation%20Mapping%20Tool%20Demo%20-%20YouTube.desktop -O " VM xMapper An Architecture-Implementation Mapping Tool Demo - YouTube.desktop"    
    sudo chown -R vagrant "/home/vagrant/Desktop"
    sudo chmod -R a+rwx "/home/vagrant/Desktop"
    
    # Remove the downloaded tar files
    sudo rm -f /home/vagrant/Desktop/eclipse.tar.gz
    sudo rm -f /home/vagrant/workspace/workspace.tar.gz
    
    # Disable screen lock, screensaver and update manager. Remove deja-dup
    wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-xMapper/raw/master/build-vm/vm-contents/screenlock_disable.sh -O /home/vagrant/Downloads/screenlock_disable.sh
    sudo chmod a+rwx "/home/vagrant/Downloads/screenlock_disable.sh"
    wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-xMapper/raw/master/build-vm/vm-contents/screenlock_disable.desktop -O "/home/vagrant/.config/autostart/screenlock_disable.desktop"
    wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-xMapper/raw/master/build-vm/vm-contents/update-notifier.desktop -O "/home/vagrant/.config/autostart/update-notifier.desktop"
    sudo apt-get remove -y deja-dup
    
    # Empty Trash
    sudo rm -rf ~/.local/share/Trash/*
    
    # Reboot the VM
    sudo reboot
    
   SHELL
end
